from game_core import *


def initialize():
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)
    print(GameSprite)


initialize()


while game:
    print('huh')
    ...